#!/bin/bash
alias ls='ls --color=auto -Fh'
alias ll='ls -l'
alias la='ll -a'
alias lr='ll -R'
alias l='ls -C'
alias c='clear'
alias traffic-cone='vlc'
alias gemacs='/usr/bin/emacs'
alias emacs='emacs -nw'

if [[ $EUID -ne 0 ]]; then
    # Other
    alias rm='rm -rf'
    alias cp='cp -rd'
    alias df='df -h'
    alias du='du -skhes'
else
    # Root
    alias rm='rm'
    alias cp='cp'
    alias df='df'
    alias du='du'
fi
