#!/bin/bash

source $HOME/.colors

#environment variables
export PATH=$PATH:$HOME/bin
export EDITOR=vim

#set the aliases I prefer
alias ls='ls --color=auto -Fh'
alias ll='ls -l'
alias la='ll -a'
alias lr='ll -R'
alias l='ls -C'
alias c='clear'

#Utilize pushd and popd
pushd()
{
  if [ $# -eq 0 ]; then
    DIR="${HOME}"
  else
    DIR="$1"
  fi
  builtin pushd "${DIR}" > /dev/null
  echo -n "DIRSTACK: "
  dirs
}
pushd_builtin()
{
  builtin pushd > /dev/null
  echo -n "DIRSTACK: "
  dirs
}
popd()
{
  builtin popd > /dev/null
  echo -n "DIRSTACK: "
  dirs
}
alias cd='pushd'
alias back='popd'
alias flip='pushd_builtin'

#set the PS1 variable
C1=$BWhite
C2=''
C3=$BBlue
C4=$BYellow
C5=$BGreen
C6=$BRed
if [[ $EUID -ne 0 ]]; then
  C2=$BYellow
else
  C2=$BRed
fi
export PS1=$C1'['$C2'\u'$C3'@'$C4'\h'$C1']'$C4'-'$C1'['$C3$VE$C5'\W'$C1']'$C4'-'$C1'['$C6'\$'$C1']'$C4'-> '$Color_Off

